version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      ssh: [default]
    ports:
      - "3000:3000"
    env_file:
    - ./frontend/.env  # Load .env for frontend
    volumes:
      - ~/.ssh:/root/.ssh:ro
    extra_hosts:
      - "github.com:140.82.113.3"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env  # Load .env for backend
    environment:
      - NODE_ENV=production
      - PORT=5000
